jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "somethingsecret"
  #authorizationStrategy: loggedInUsersCanDoAnything
  authorizationStrategy: unsecured